/* GENERATED by tools/sync-questions.py from questions.json — do not edit here.
   The eight stages of the journey, in order. Every band, the answers strip, Move and the
   tools read this; the wording is decided in questions.json and nowhere else. */
window.ETHICARE_JOURNEY = [
  { n: 1, id: "imagine", label: "Imagine the possibilities", there: "Imagine the possibilities", where: "Just imagining it", href: {"nz": "/new-zealand", "au": "/australia", "any": "/"}, questions: [] },
  { n: 2, id: "choose", label: "Choose your destination", there: "Choose your destination", where: "Choosing between the two countries", href: {"nz": "/destinations/", "au": "/destinations/australia", "any": "/australia-vs-new-zealand"}, questions: [] },
  { n: 3, id: "work", label: "Can I work here?", there: "Can I work there?", where: "Checking whether I can register", href: {"nz": "/guides/new-zealand-registration", "au": "/guides/australia-registration", "any": "/can-i-work-there"}, questions: ["work"] },
  { n: 4, id: "numbers", label: "Make the numbers work", there: "Make the numbers work", where: "Working out the money", href: {"nz": "/what-could-i-earn", "au": "/what-could-i-earn", "any": "/what-could-i-earn"}, questions: ["earn", "afford"] },
  { n: 5, id: "place", label: "Where could we live?", there: "Where could we live?", where: "Deciding where we would live", href: {"nz": "/destination-finder", "au": "/destination-finder", "any": "/destination-finder"}, questions: ["live"] },
  { n: 6, id: "role", label: "What jobs could I get?", there: "What jobs could I get?", where: "Looking for the right role, or applying", href: {"nz": "/jobs/", "au": "/jobs/", "any": "/jobs/"}, questions: ["jobs"] },
  { n: 7, id: "plan", label: "How do we plan it all?", there: "How do we plan it all?", where: "Offer accepted \u2014 planning the move", href: {"nz": "/plan", "au": "/plan", "any": "/plan"}, questions: ["plan"] },
  { n: 8, id: "settle", label: "Settle into life", there: "Settle into life", where: "Already here", href: {"nz": "/settling-in", "au": "/settling-in", "any": "/settling-in"}, questions: [] }
];
window.ETHICARE_JOURNEY_MAP = {
  "moveToJourney": {
    "exploring": "imagine",
    "applying": "role",
    "offer": "role",
    "moving": "plan",
    "arrived": "settle"
  },
  "journeyToMove": {
    "imagine": "exploring",
    "choose": "exploring",
    "work": "exploring",
    "numbers": "exploring",
    "place": "exploring",
    "role": "applying",
    "plan": "moving",
    "settle": "arrived"
  }
};
